server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://replica1:8002/eureka/
  instance:
    localhost: replica2
    