server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: macro
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://macro:123456@localhost:8004/eureka/
  instance:
    localhost: localhost